'use client';

import { useState } from 'react';
import { generateAiMenu } from '../lib/commands';
import type { AiConfig, AiMealRow, MealTime, Targets } from '../lib/types';

export default function AiMealPlanner({ meals, targets, onImplement }: { meals: MealTime[]; targets: Targets; onImplement: (rows: AiMealRow[]) => void }) {
  const [config, setConfig] = useState<AiConfig>({ provider: 'openrouter', model: '', apiKey: '', baseUrl: '' }); const [rows, setRows] = useState<AiMealRow[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const patch = (value: Partial<AiConfig>) => setConfig(current => ({ ...current, ...value }));
  return <section><div className="section-header"><div><h2>AI Meal Planner Integration</h2><p>Generate customized nutritional plans.</p></div></div><div className="ai-grid"><div className="card form-grid"><h3>Configuration</h3><label>AI Provider<select value={config.provider} onChange={event => patch({ provider: event.target.value })}><option value="openrouter">OpenRouter</option><option value="openai">OpenAI</option><option value="google">Google Project</option><option value="anthropic">Anthropic</option><option value="custom">Custom Router</option></select></label>{config.provider === 'custom' && <label>Base URL<input type="url" value={config.baseUrl} onChange={event => patch({ baseUrl: event.target.value })} /></label>}<label>Model<input value={config.model} onChange={event => patch({ model: event.target.value })} /></label><label>API Key<input type="password" value={config.apiKey} onChange={event => patch({ apiKey: event.target.value })} /></label><button className="primary full" disabled={loading} onClick={async () => { setError(''); if (!config.model || !config.apiKey || targets.kcal <= 0) return setError('Model, API key, dan TDEE wajib diisi.'); setLoading(true); try { const result = await generateAiMenu({ targetTDEE: Math.round(targets.kcal), targetCarbs: Math.round(targets.carbs), targetProtein: Math.round(targets.protein), targetFat: Math.round(targets.fat), availableMealTypes: meals.map(meal => meal.label), aiConfig: { ...config, baseUrl: config.baseUrl || ({ openrouter: 'https://openrouter.ai/api/v1', openai: 'https://api.openai.com/v1', google: 'https://generativelanguage.googleapis.com/v1beta', anthropic: 'https://api.anthropic.com/v1' }[config.provider] || '') } }); setRows(result); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Gagal generate AI menu'); } finally { setLoading(false); } }}>{loading ? 'Memproses...' : 'Generate AI Meal Plan'}</button>{error && <p className="error">{error}</p>}</div><div className="card ai-results"><h3>Analysis Results</h3>{rows.length === 0 ? <p className="muted">Belum ada preview.</p> : <><div className="table-scroll"><table><thead><tr><th>Waktu</th><th>Makanan</th><th>Gram</th><th>Kalori</th><th>Protein</th><th>Lemak</th><th>Karbo</th><th>Alasan</th></tr></thead><tbody>{rows.map((row, index) => <tr key={`${row.matched_food_id}-${index}`}><td>{row.meal_type}</td><td>{row.matched_food_name || row.requested_keyword}</td><td>{row.suggested_grams}</td><td>{row.calories.toFixed(1)}</td><td>{row.protein.toFixed(1)}</td><td>{row.fat.toFixed(1)}</td><td>{row.carbohydrate.toFixed(1)}</td><td>{row.reasoning}</td></tr>)}</tbody></table></div><button className="primary" onClick={() => onImplement(rows)}>Implementasikan Plan ke Dashboard</button></>}</div></div></section>;
}
