'use client';

import { useState } from 'react';
import { getRecommendations } from '../lib/commands';
import type { FoodResult, NutrientSummary, RecommendationFilter } from '../lib/types';

export default function Recommendations({ nutrients, onAdd }: { nutrients: NutrientSummary[]; onAdd: (food: FoodResult) => void }) {
  const [filters, setFilters] = useState<RecommendationFilter[]>([{ nutrient: nutrients[0]?.name || 'energi', operator: '<', value: 100 }]); const [results, setResults] = useState<FoodResult[]>([]); const [loading, setLoading] = useState(false);
  const update = (index: number, patch: Partial<RecommendationFilter>) => setFilters(current => current.map((filter, item) => item === index ? { ...filter, ...patch } : filter));
  return <section><div className="section-header"><div><h2>Rekomendasi Makanan</h2><p>Cari makanan berdasarkan batas nutrisi.</p></div></div><div className="dashboard-grid"><div className="card"><h3>Filter Nutrisi</h3>{filters.map((filter, index) => <div className="filter-row" key={index}><select value={filter.nutrient} onChange={event => update(index, { nutrient: event.target.value })}>{nutrients.map(nutrient => <option key={nutrient.name}>{nutrient.name}</option>)}</select><select value={filter.operator} onChange={event => update(index, { operator: event.target.value as RecommendationFilter['operator'] })}><option value="<">&lt;</option><option value=">">&gt;</option><option value="=">=</option></select><input type="number" value={filter.value} onChange={event => update(index, { value: Number(event.target.value) })} /><button onClick={() => setFilters(current => current.filter((_, item) => item !== index))}>×</button></div>)}<button onClick={() => setFilters(current => [...current, { nutrient: nutrients[0]?.name || 'energi', operator: '<', value: 100 }])}>+ Filter</button><button className="primary full" disabled={loading} onClick={async () => { setLoading(true); try { setResults(await getRecommendations(filters)); } finally { setLoading(false); } }}>{loading ? 'Mencari...' : 'Cari Rekomendasi'}</button></div><div className="card"><h3>Hasil Rekomendasi</h3>{results.length === 0 && <p className="muted">Belum ada hasil.</p>}{results.map(food => <div className="recommendation" key={food.id}><span><b>{food.name}</b><small>{food.category || 'Umum'}</small></span><button onClick={() => onAdd(food)}>+ Tambah</button></div>)}</div></div></section>;
}
