'use client';

import { useState } from 'react';
import { calculateTdee } from '../lib/commands';
import type { Targets } from '../lib/types';

export default function TdeeCalculator({ onTargets }: { onTargets: (targets: Targets) => void }) {
  const [form, setForm] = useState({ gender: 'Male', weightKg: 70, heightCm: 170, age: 25, activityFactor: 1.2, injuryFactor: 1 }); const [perc, setPerc] = useState({ carbs: 50, protein: 20, fat: 30 }); const [result, setResult] = useState<Targets | null>(null); const [error, setError] = useState('');
  const setField = (key: keyof typeof form, value: string) => setForm(current => ({ ...current, [key]: key === 'gender' ? value : Number(value) } as typeof form));
  return <section><div className="section-header"><div><h2>Kalkulator TDEE & Target Nutrisi</h2><p>Hitung kebutuhan energi dan distribusi makro.</p></div></div><div className="dashboard-grid"><div className="card form-grid"><h3>Data Fisik & Klinis</h3><label>Jenis Kelamin<select value={form.gender} onChange={event => setField('gender', event.target.value)}><option>Male</option><option>Female</option></select></label><label>Berat Badan (kg)<input type="number" value={form.weightKg} onChange={event => setField('weightKg', event.target.value)} /></label><label>Tinggi Badan (cm)<input type="number" value={form.heightCm} onChange={event => setField('heightCm', event.target.value)} /></label><label>Usia<input type="number" value={form.age} onChange={event => setField('age', event.target.value)} /></label><label>Faktor Aktivitas<input type="number" step="0.1" value={form.activityFactor} onChange={event => setField('activityFactor', event.target.value)} /></label><label>Faktor Cedera<input type="number" step="0.1" value={form.injuryFactor} onChange={event => setField('injuryFactor', event.target.value)} /></label></div><div className="card form-grid"><h3>Distribusi Makronutrien (%)</h3>{(['carbs', 'protein', 'fat'] as const).map(key => <label key={key}>{key}<input type="number" value={perc[key]} onChange={event => setPerc(current => ({ ...current, [key]: Number(event.target.value) }))} /></label>)}{error && <p className="error">{error}</p>}<button className="primary full" onClick={async () => { if (Math.abs(perc.carbs + perc.protein + perc.fat - 100) >= 0.1) return setError('Total harus 100%!'); setError(''); const response = await calculateTdee(form); const targets = { kcal: response.totalDailyEnergyExpenditure, carbs: response.totalDailyEnergyExpenditure * perc.carbs / 100 / 4, protein: response.totalDailyEnergyExpenditure * perc.protein / 100 / 4, fat: response.totalDailyEnergyExpenditure * perc.fat / 100 / 9 }; setResult(targets); onTargets(targets); }}>Hitung & Terapkan</button></div></div>{result && <div className="card result-grid"><div><small>TDEE</small><b>{result.kcal.toFixed(0)} kcal</b></div><div><small>Karbo</small><b>{result.carbs.toFixed(1)} g</b></div><div><small>Protein</small><b>{result.protein.toFixed(1)} g</b></div><div><small>Lemak</small><b>{result.fat.toFixed(1)} g</b></div></div>}</section>;
}
